name: Firebase Hosting部分の確認

on: [push]

jobs:
  check_firebase_hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'
      - run: npm install
      - run: npm run-script build
      - run: npm test
